import = [
  "~/.config/alacritty/themes/themes/github_dark.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

opacity = 0.9
blur = true

option_as_alt = "Both"

[font]
normal.family = "MesloLGS NF"
